### ISSUE TITLE
 Problem reading QR codes on Android 64 bit devices

### ISSUE THREAD

**Issue by sinuke** [Spelt/ZXing.Delphi#93] opened 2020-02-12 08:01 UTC
Hello

I have problem with reading qr codes on android 64 devices. My code is working correctrly on android 32-bit devices. For example with this qr code i have problem.

![123](https://user-images.githubusercontent.com/25010867/74314640-d142e500-4d86-11ea-9c7c-2c56c256ff7a.png)

I'm using Embarcadero Delphi 10.3.3 and latest version of ZXing.Delphi

**Comment by Spelt** [comment] 2020-02-12 18:48
Thanks for the report and failing case. 
I will take a look at it soon.

**Comment by GubaidullinLR** [comment] 2020-02-26 09:58
Hello, a similar problem with barcode recognition on the 64-bit version of Android. But I can read the above stroke, but others can't.
Although in version 32, these codes read well.
Thank you for your work. You greatly facilitate the work of many thousands of people


![IMG_20200226_123806](https://user-images.githubusercontent.com/61496495/75333397-23abf780-5897-11ea-93b5-f4dcb38aeebf.jpg)

![IMG_20200226_123753](https://user-images.githubusercontent.com/61496495/75333406-26a6e800-5897-11ea-95c1-692850345928.jpg)

**Comment by GubaidullinLR** [comment] 2020-02-26 10:23
The problem is probably the same as in the post Problem reading QR codes on iOS 11.2 64 bit devices

**Comment by Spelt** [comment] 2020-03-07 17:14
It should be fixed in v3.9.0.

Can you test it?

Please reopen if not.

**Closed as completed by Spelt** 2020-03-07 17:14 UTC

**Comment by Fatma-debug-cloud** [comment] 2024-08-31 16:05
Hellow I have problem with reading code with my Android Samsung A71

![17251203113522555949857715818265](https://github.com/user-attachments/assets/723fa52e-10a8-4dd0-8f6e-8b0126837f1d)

**Comment by Spelt** [comment] 2024-09-01 19:14
HiAfter quick online test  I noticed that the qr code does not work with the zxing online decoder. zxing.orgAlso it did not work with: https://4qrcode.com/scan-qr-code.phpI think this is not a good QR. If I look at the QR code I think its missing white space around it. Op 31 aug 2024 om 18:05 heeft Fatma-debug-cloud ***@***.***> het volgende geschreven:﻿
Hellow I have problem with reading code with my Android Samsung A71
17251203113522555949857715818265.jpg (view on web)
